#!/bin/sh

export LC_CTYPE="en_US.UTF-8"
OS=$(uname)
LPREFIX=/usr/local

if [ $OS != "OpenBSD" ]; then
	LPREFIX=/usr
fi

mkfifo /tmp/pianobar

xset -b &

if [ -x ${LPREFIX}/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-session`
fi

if [ -f ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap &
fi

if [ -e ${LPREFIX}/bin/tpb ]; then
	${LPREFIX}/bin/tpb -d
fi

if [ -x ${LPREFIX}/bin/scmpc ]; then
	${LPREFIX}/bin/scmpc &
fi

if [ -x ${LPREFIX}/bin/scmpc ]; then
	${LPREFIX}/bin/scmpc &
fi

#if [ -x ${LPREFIX}/bin/redshift-gtk ]; then
#	redshift-gtk &
#fi

#if [ -x ~/bin/sctd ]; then
if [ -x ${LPREFIX}/bin/sctd ]; then
	${LPREFIX}/bin/sctd &
fi

if [ -x ${LPREFIX}/bin/xfce4-clipman ]; then
	xfce4-clipman &
fi

xset +fp ~/.fonts
for font in $(ls /usr/local/share/fonts/); do
	xset +fp /usr/local/share/fonts/${font}
done
xset fp rehash

xrdb -merge -load ~/.Xresources &

xidle -delay 5 -sw -program "/usr/X11R6/bin/xlock" -timeout 300 &

#exec xmonad-x86_64-openbsd
exec awesome
#exec cwm
