#!/bin/ksh

set -A paths /usr/games \
	~/dev/go/bin \
    	/usr/ports/infrastructure/bin \
	/usr/pkg/bin \
	/usr/pkg/sbin \
	~/bin \
	~/.bin \
	~/go/bin \
	~/ruby_bin/bin \
	~/.dcolor \
	~/.cargo/bin \
	/usr/local/plan9/bin/

for d in "${paths[@]}"; do
	[[ -d "${d}" ]] && PATH="${PATH}:$d"
done
