#!/bin/sh

cat /dev/null > ~/.xsession-errors

. ~/.ksh_paths

LC_CTYPE="en_US.UTF-8"
TERM=screen-256color
export LC_CTYPE TERM

OS=$(uname)
LPREFIX=/usr/local

wmanager=$(cat ~/.wmanager 2> /dev/null || echo "/usr/X11R6/bin/cwm")

if [ $OS != "OpenBSD" ]; then
	LPREFIX=/usr
fi

xset -b &
xset +fp ~/.fonts
for font in /usr/local/share/fonts/*; do
	xset +fp "${font}"
done
xset fp rehash

xrdb -merge -load ~/.Xresources &

if [ -x ${LPREFIX}/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-session`
fi

get_font() {
	grep "$1" ~/.Xdefaults | awk -F: '{sub(/^ +/, "", $2); print $2 ":" $3}'
}

echo "FONT NAME: $(get_font '^XTerm*face')"

case "$wmanager" in
	/usr/X11R6/bin/cwm)
		xsetroot -solid black
		while true; do ~/bin/bar; sleep 5; done | lemonbar -d \
			-f "$(get_font '^XTerm\*face')" \
			-B "#2E3440" \
			-F "#D8DEE9" | sh &
		/usr/X11R6/bin/xcompmgr &
		;;
	/usr/local/bin/awesome)
		xsetroot -solid black
		;;
	xmonad-x86_64-openbsd)
		hsetroot -center ~/.background.png &
		;;
	/usr/X11R6/bin/fvwm)
		xsetroot -solid black
		;;
esac

if [ -f ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap &
fi

if [ -e ${LPREFIX}/bin/tpb ]; then
	${LPREFIX}/bin/tpb -d
fi

if [ -e ${LPREFIX}/bin/xbanish ]; then
	${LPREFIX}/bin/xbanish &
fi

if [ -x ${LPREFIX}/bin/scmpc ]; then
	${LPREFIX}/bin/scmpc &
fi

if [ -x ${LPREFIX}/bin/sctd ]; then
	${LPREFIX}/bin/sctd &
fi

TIMEOUT=$(cat ~/.xtimeout 2> /dev/null || echo "300")
xidle -delay 5 -program "/usr/X11R6/bin/xlock" -timeout $TIMEOUT &

if [ -e ${LPREFIX}/bin/keychain ]; then
	${LPREFIX}/bin/keychain --gpg2 --inherit any --agents ssh,gpg -q -Q
	keychain_conf="$HOME/.keychain/$(uname -n)-sh"

	# shellcheck source=/home/qbit/.keychain/slip.bold.daemon-sh
	[ -e "${keychain_conf}" ] && . ${keychain_conf}

	# shellcheck source=/home/qbit/.keychain/slip.bold.daemon-sh-gpg
	[ -e "${keychain_conf}-gpg" ] && . ${keychain_conf}-gpg
fi

if [ -e ${LPREFIX}/bin/ssh-agent-card-prompt ]; then
	${LPREFIX}/bin/ssh-agent-card-prompt &
fi

exec "$wmanager"
