#!/bin/sh

cat /dev/null > ~/.xsession-errors

. ~/.ksh_paths

LC_CTYPE="en_US.UTF-8"
TERM=screen-256color
export LC_CTYPE TERM

OS=$(uname)
LPREFIX=/usr/local

wmanager=$(cat ~/.wmanager 2> /dev/null || echo "/usr/X11R6/bin/cwm")

if [ $OS != "OpenBSD" ]; then
	LPREFIX=/usr
fi

xset -b &

if [ -x ${LPREFIX}/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-session`
fi

case "$wmanager" in
	/usr/X11R6/bin/cwm)
		xsetroot -solid black
		xbattbar -i green -o "olive drab" -I blue -O red &
		/usr/X11R6/bin/xcompmgr &
		;;
	/usr/local/bin/awesome)
		xsetroot -solid black
		;;
	xmonad-x86_64-openbsd)
		feh --bg-center ~/.background.png &
		;;
	/usr/X11R6/bin/fvwm)
		xsetroot -solid black
		;;
esac

if [ -f ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap &
fi

if [ -e ${LPREFIX}/bin/tpb ]; then
	${LPREFIX}/bin/tpb -d
fi

if [ -e ${LPREFIX}/bin/xbanish ]; then
	${LPREFIX}/bin/xbanish &
fi

if [ -x ${LPREFIX}/bin/scmpc ]; then
	${LPREFIX}/bin/scmpc &
fi

if [ -x ${LPREFIX}/bin/sctd ]; then
	${LPREFIX}/bin/sctd &
fi

xset +fp ~/.fonts
for font in /usr/local/share/fonts/*; do
	xset +fp "${font}"
done
xset fp rehash

xrdb -merge -load ~/.Xresources &

TIMEOUT=$(cat ~/.xtimeout 2> /dev/null || echo "300")
xidle -delay 5 -program "/usr/X11R6/bin/xlock" -timeout $TIMEOUT &

pgrep -q emacs || (emacs --daemon &)

exec "$wmanager"
