#!/bin/ksh

set -A paths /usr/games \
    	/usr/ports/infrastructure/bin \
    	/usr/local/jdk-1.8.0/bin \
	/usr/pkg/bin \
	/usr/pkg/sbin \
	~/bin \
	~/.bin \
	~/go/bin \
	~/node_bin/node_modules/.bin \
	~/ruby_bin/bin \
	~/.dcolor \
	~/dev/depot_tools \
	~/.cabal/bin \
	~/.cargo/bin \
	/usr/local/plan9/bin/

for d in "${paths[@]}"; do
	[[ -d "$d" ]] && PATH="${PATH}:$d"
done
