#!/bin/sh

cat /dev/null > ~/.xsession-errors

. ~/.ksh_paths

LC_CTYPE="en_US.UTF-8"
TERM=screen-256color
export LC_CTYPE TERM

OS=$(uname)
LPREFIX=/usr/local

wmanager=$(cat ~/.wmanager 2> /dev/null || echo "/usr/X11R6/bin/cwm")

if [ $OS != "OpenBSD" ]; then
	LPREFIX=/usr
fi

xset -b &
xset +fp ~/.fonts
for font in /usr/local/share/fonts/*; do
	xset +fp "${font}"
done
xset fp rehash

xrdb -merge -load ~/.Xresources &

if [ -x ${LPREFIX}/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-session`
fi

get_font() {
	grep "$1" ~/.Xdefaults | awk -F: '{sub(/^ +/, "", $2); print $2 ":" $3}'
}

echo "FONT NAME: $(get_font '^XTerm*face')"

case "$wmanager" in
	/usr/X11R6/bin/cwm)
		xsetroot -solid black
		while true; do ~/bin/bar; sleep 3; done | lemonbar-xft -d \
			-f "$(get_font '^XTerm\*face')" \
			-B "#FFFFEA" \
			-F "#000000" | sh &
		/usr/X11R6/bin/xcompmgr &
		;;
	/usr/local/bin/awesome)
		xsetroot -solid black
		;;
	xmonad-x86_64-openbsd)
		hsetroot -center ~/.background.png &
		;;
	/usr/X11R6/bin/fvwm)
		xsetroot -solid black
		;;
esac

if [ -f ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap &
fi

if [ -d /usr/local/plan9/ ]; then
	pgrep -q fontsrv || (/usr/local/plan9/bin/fontsrv &)
	pgrep -q plumber || (/usr/local/plan9/bin/plumber &)
fi

for tool in tpb xbanish scmpc sctd autocutsel keychain; do
	if [ -e "${LPREFIX}/bin/${tool}" ]; then
		case "${i}" in
			tpb)
				${LPREFIX}/bin/tpb -d
				;;
			keychain)
				${LPREFIX}/bin/keychain --gpg2 --inherit any --agents ssh,gpg -q -Q
				keychain_conf="$HOME/.keychain/$(uname -n)-sh"

				# shellcheck source=/home/qbit/.keychain/slip.bold.daemon-sh
				[ -e "${keychain_conf}" ] && . ${keychain_conf}

				# shellcheck source=/home/qbit/.keychain/slip.bold.daemon-sh-gpg
				[ -e "${keychain_conf}-gpg" ] && . ${keychain_conf}-gpg
				;;
			*)
				${LPREFIX}/bin/${tool} &
				;;
		esac
	fi
done

TIMEOUT=$(cat ~/.xtimeout 2> /dev/null || echo "300")
xidle -delay 5 -program "/usr/X11R6/bin/xlock" -timeout $TIMEOUT &

exec "$wmanager"
